from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "customer" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "customerauth" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'valid',
    "access_token" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "customer_id" INT NOT NULL REFERENCES "customer" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "order" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'created',
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "orderitem" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "price" INT NOT NULL,
    "amount" INT NOT NULL DEFAULT 1,
    "order_id" INT NOT NULL REFERENCES "order" ("id") ON DELETE CASCADE,
    "product_id" INT NOT NULL REFERENCES "order" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "seller" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "sellerauth" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'valid',
    "access_token" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "seller_id" INT NOT NULL REFERENCES "seller" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "store" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "seller_id" INT NOT NULL REFERENCES "seller" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "product" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT NOT NULL,
    "price" INT NOT NULL,
    "external_id" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "store_id" INT NOT NULL REFERENCES "store" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSON NOT NULL
);"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """


MODELS_STATE = (
    "eJztm21v2joUx78K4lUn9U4rt3vQfUcZveNuhapwt2nTFLmJC1ETm8XOKJr47rOdOHEeS1"
    "qonOJX646PE/vnE59/Tszvro8d6JGXg5BQ7MOg+0/ndxcBH7I/Cm3HnS5YLtMWbqDg2hPO"
    "tup1TWgAbMrsN8AjkJkcSOzAXVIXI2ZFoedxI7aZo4vmqSlE7s8QWhTPIV2I8Xz/wcwucu"
    "AdJPK/y1vrxoWekxmu6/B7C7tF10thGyF6Lhz53a4tG3uhj1Ln5ZouMEq8XUS5dQ4RDACF"
    "/PI0CPnw+ejimcoZRSNNXaIhKn0ceANCjyrT3ZKBjRHnx0ZDxATn/C5/9U5O356++/vN6T"
    "vmIkaSWN5uoumlc486CgLjWXcj2gEFkYfAmHIT/xbIDRYgKEcn/XPw2JDz8CSqOnrSkOJL"
    "Q2ZH/HxwZ3kQzemCQ3v9uobW5/7V4EP/6oh5veCzwSyMo/gex029qI0jTRFCH7heE4ZJh9"
    "1A3HsI7h/hEhCywkHJM1xNUe1jojFBaQeQT9kCtAjzPWuhrg/LgWZ75pA6cdeX8g9NAbM5"
    "OBPkrePHoIbvbHQxnM76F5d8Jj4hPz2BqD8b8paesK5z1qM3uaVILtL5Mpp96PD/dr5Nxk"
    "NBEBM6D8QdU7/Zty4fEwgpthBeWcBRnlhplWA2PN3d3CobNzdcA/t2BQLHyrQoERAnY4td"
    "blEMgrO4+/nHK+gBAbi43Lns34+vpN+Cb2QUS6tceE4K93AVu2KT3/PzFoDAXIya35vfqQ"
    "xLjWiS2O4XTnKpjHhqk3giFNCQNElaaY+nS1ndX8CLFk3frAVsGxLCgvcWoiY88/2MEDBC"
    "4DkKgczCyvzeaNvO9bp//9ZkHXewhRdUVJFlEeQ5DqA7Rx/hWvAcsVEBZJe9+5ZUSvTjWK"
    "WTmDkAq0QT5MOETZNNDtJoG+5PB/33w+6mWoXuU3VNAqe8RhU11OosnLgYgaXZ0/kMBFac"
    "MPWWWEYPPCM98KDCgNgEXQp9K9kOH14aEJvuiF1Mz/WurAtkyo4BdkKbHjKOvSdswaQqaU"
    "tg9yRuV7qZ5N2i5L0MXLvk21IlusT/kN5NMkUQH4eoJDtXEks7PB2yE314ib2h2Vuw2uVQ"
    "w0xmvUbgsp0OCV1N9aBCNzQuHSQvsPoR3LZuoD5Y5UWDkhA06IqPlk4Vl8t4mUrk22W6gt"
    "XiTVlmI91029fqpJs5FfTocos6sgLJGbyrCMJct7YArSunDL/OMpUUie3oov/1Raaa8mky"
    "/le6K5gHnyZnBQ1j3i0aiT4WcDBAwCtVfdXhmOtmwrE8HE1t9RnVVtWFJZQJ0mZvSmqXQ9"
    "ptat6TBJIdiP2pvI5+BLcV+2p06CT1p9Dzyr+uxi3HdUKfpD5G52v2XB4bnW9O/2uN0Jz+"
    "Nx/5jRDd0Uf+KBXv4Ox/lPdbePI/o98jGniFHvuBv4Xac68f95XwqBSN9//+IVof8+uHNo"
    "rHlhzOM79+0G7DMkLICKEHV+SijN6sJKf2MTW5XMnmsUW55EL6Mdy6KqcGiFZlOaE6ywSW"
    "lKM12ipxMbJKs+eyTlaZmpxJ/ib5m+Rvkn8bkn/+U3HlycYmtSblcF17sO612tSHgWuXVp"
    "rillolBFIfI4U026XqpNAvGJDS83PVakjpYgRRWmBij0YDiLF7OwGevHq1BUDmVQlQtOUU"
    "JUYUlv0257/pZFwhJdMuOZD/IzbB745r0+OO5xL6Q0+sNRT5rDOSsXCILn9eLqcF+QXOyj"
    "TKU75mb/4A9ASvGQ=="
)
