from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "seller" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "sellerauth" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'valid',
    "access_token" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "seller_id" INT NOT NULL REFERENCES "seller" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "store" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "credential" VARCHAR(255) NOT NULL,
    "commission_percentage" VARCHAR(40) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "seller_id" INT NOT NULL REFERENCES "seller" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "customer" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "store_id" INT NOT NULL REFERENCES "store" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "cart" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "customer_id" INT NOT NULL REFERENCES "customer" ("id") ON DELETE CASCADE,
    "store_id" INT NOT NULL REFERENCES "store" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "customerauth" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'valid',
    "access_token" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "customer_id" INT NOT NULL REFERENCES "customer" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "order" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'created',
    "code" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "customer_id" INT NOT NULL REFERENCES "customer" ("id") ON DELETE CASCADE,
    "store_id" INT NOT NULL REFERENCES "store" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "product" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'active',
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT NOT NULL,
    "price" INT NOT NULL,
    "product_code" TEXT NOT NULL,
    "park_code" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "store_id" INT NOT NULL REFERENCES "store" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "cartitem" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "amount" INT NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "cart_id" INT NOT NULL REFERENCES "cart" ("id") ON DELETE CASCADE,
    "product_id" INT NOT NULL REFERENCES "product" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "orderitem" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "price" INT NOT NULL,
    "amount" INT NOT NULL DEFAULT 1,
    "order_id" INT NOT NULL REFERENCES "order" ("id") ON DELETE CASCADE,
    "product_id" INT NOT NULL REFERENCES "product" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSON NOT NULL
);"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """


MODELS_STATE = (
    "eJztnVtT2zgUx79KJk90JtuBLLSdfQshbLMF0oHsbqedjkfYImiw5dSWuUyH715JtnyL7M"
    "SNE+xwngBZkqVfdPmfo6Pws+u4Frb9t0Pkse5fnZ9dihzMf8mk9zpdNJ8nqSKBoWtbZjRV"
    "jmufecgUtdwg28c8ycK+6ZE5Iy7lqTSwbZHomjwjobMkKaDkR4AN5s4wu8Uef/DtO08m1M"
    "KP2Fd/zu+MG4JtK9NMYol3y3SDPc1l2piyU5lRvO3aMF07cGiSef7Ebl0a5yZUNn+GKfYQ"
    "w6J65gWi+aJ1US9Vj8KWJlnCJqbKWPgGBTZLdXdFBqZLBT/eGl92cCbe8kf/4PD94Yc/3x"
    "1+4FlkS+KU989h95K+hwUlgYtp91k+RwyFOSTGhJvPEAv8RXbDW+Tp4SUlcgB5s/MAFa4y"
    "giohQZgMG8Wwy8cTucfdNTg66NGwMZ2xWwHv6KiE2n+Dy+HHweUez/VGvNLlwzkc4xfRo3"
    "74TKBNUJoeFt02EFvEecKfMOJgPdJsyRxWKyr6Vv2yKchrDlTeB2tC7adoDpTwnY7PR1fT"
    "wfln0RPH93/YEtFgOhJP+jL1KZe69y73UcSVdP4fTz92xJ+dr5OLkSTo+mzmyTcm+aZfu6"
    "JNKGCuQd0HA1mp6apSFZjsBxv4zHWwZ1RaZHKllq82Dfkca1lw0guM6+Fq5NJFXhM2sbnd"
    "3BUs0xzJIsJTnkpm9BN+kiTHvEmImlgDLtrGr1Q9zSP4rIaBSk1mp4ce4i0/Mzp4B3m3MA"
    "u3rMHVcHAy6mrnbg3shqmq2osvtyzpCYqReI3MuwfkWUbBkBR6jzDsGEr4ZfEeR8VPP11i"
    "G8neFJPlNYx5Ve0iKym5fTdFJ8Nt8ZHTd/IpiKKZbLV4t3hTHkmBFle4yvU4UblAkzdsrS"
    "/T5MhxA6qZUoXskgLb2y4PXpofCO/dF958CasoupMSr0k5pqHNPdcKzIrcsoVeE7oS0a0X"
    "NtV1Y1RN8/itrBmTWbVccUdDqQZwn5Oa2ssuO7Oqyu2NSkxlz+gkZsrWKZGY6VwgMRu2sp"
    "VJTPlzgVyx01fl357Ld01+m3f3YgcRuwrDuEA9EDc+BDePcI58/8H1NHO4mGK6DIxGsIF2"
    "3QYC/zn4z2sVpMv956t6f41i53pV72+7kOpPB/k0vl2TRFTVIKqppUT47sxx1DM4JqKulr"
    "HYhtEmh0iJ4aaG0HLjTQ1bMOCatp/12h+3c4/s8ENrrnJGpol9nw/eO0yr8MyXA2MEjJFd"
    "N0YgEqrG0wWITKk1MmWTqitUoRq5FcvTYp3lxllAYDVsdu6AwIo2zGZLLJPPiiokVX6QVC"
    "CpQFKBpILgcnCON8U5DsHl2wgul6JZRpfH8nlNHzLEly9aNEUB5hlgSywbCDFvo3Uz94ip"
    "WfJL4kOJdvXa6S0z4yWGmPxKvMIzwErTM13ktQ4zCN6uS9QW6IbKwqyFB9B5VZaeWBC/vT"
    "Px2wqvRsClyBfLt9QHDeKtaStbmXhriWu6Dd/ZAXHwayNMt2yB5BQ/FsznXLG2AC3zPI++"
    "TDNOZ4Vt73zw5U3G8Xw2ufhbZU9hHp5NjhcEIRhqv6Wg9WdOxeMxXw4GZMGARN5ddbjpQk"
    "BWTxaO+Hb0iA9OqeCUqsqKs6UrHPGOl/qimPVucbTwjEUnHTLnGnDsVKfP4grbtj6SLnrS"
    "K/NY+EkecFg0bOXulTgswMqG2+YvjxBum0M0Ipgqi6bKguZeRTyGW3ENd17Dfb/lN14jGu"
    "4DXTdWqYXWyRYEY9Ft1+zgWSYc4aZrG8VjS0674KZr4xYsEEIghH7bZxvu6NWctuky4LXN"
    "uWzWddvGFTWP4cp+2/QAaVIoUag6dQJLydESbRVnAVnVsHlZJqvAJ1fH5m9hygiq5JjLlg"
    "KcqVvCjkN8nzfMmGPP5Iz4YqWRVdgkDrIL4BbVkRdYYSVvo8o2xXx/7T1Fx/dkNByfD872"
    "jnp9yZfLJhJuI4r84T4IVRCqIFRBqL6AUM0HvtTz/4HaBVQT/1PTl2W28p6wBkdd93pbD6"
    "Lwvk0VFK28arPRg4MB9oipPTSInvTKjFqU5AGrtmGbeK/Eqr3Hnq+9iFBsj6WKgDGWnBXw"
    "qVEBYpS9nQAP9vdXAMhzFQKUz/LWLGVYd2P8n6vJRZHxGhfJgfyX8g5+s4jJeh2b+Ox7M7"
    "GWUBS9zlhUCxHz+eD4XtZUEhUc6yT8Nj2mz78AwA9hMg=="
)
